language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: linux
      sudo: required
      python: 3.5
    - os: osx
      language: generic
      osx_image: xcode7.3

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
      sudo apt-get -y purge libgraphviz-dev;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      sudo easy_install nose;
    fi
  - pip install -r ./python/requirements.txt

script: 
  - cd python
  - python setup.py build_ext --inplace
  - nosetests -s -v