language: c

os:
- osx
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    sudo apt-get update;
    sudo apt-get -y purge libgraphviz-dev;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    brew update;
    sudo easy_install pip;
  fi

install:
- sudo pip install -r ./python/requirements.txt

script: 
- cd python
- python setup.py build_ext --inplace
- nosetests -s -v